# Generated by Django 2.2 on 2021-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_clean', models.BooleanField(default=True)),
            ],
        ),
    ]
